site_name: Picasso Auth
nav:
    - Home: index.md
    - Identificación de aplicaciones: App_setup.md
    - Pasos para crear un JWT: JWT_build.md
    - Solicitar un token de autenticación: JWT_request.md
    - Depósito con activación: Deposit.md
    - Anulación de un depósito: DepositRefund.md
    Reversos:
      - De depósito con activación: DepositReverse.md
      - De anulación: DepositRefundReverse.md
theme: readthedocs
